### ISSUE TITLE
Cannot cool SX-56 camera and no results after successful run.

### ISSUE THREAD

**Issue by InFINNity-Deck** [mworion/MountWizzard4#156]
Hi Michel,

the past few months I have been assisting a Canadian GM3000 owner. Today we did a successful 74-point run, but we did experience two issues, see attached log-file.
[mw4-2021-06-27.zip](https://github.com/mworion/MountWizzard4/files/6721513/mw4-2021-06-27.zip)

We started out with version 0.152.0b6. After an initial partial run I wanted to see if with version 1.1.1 could fill in the gaps as 0.152.0b6 did not allow to do so (the option "Exclude Successful Points..." was greyed out), so the log-file contains runs with both versions.

With version 0.152.0b6 we could cool the camera (SX-56 over ASCOM), but after installing 1.1.1 this was no longer possible. Good thing about 1.1.1 is that the image window now shows the CCD temperature for this camera (that did not work in 0.152.0b6). We solved the cooling-issue by using MaximDL to control the cooling, but of course it would be nice to have this "Cool on" button working again.

Finally we did this 74 point run, which resulted in a 22 term model with a RMS of 7.4" and a PAE of 50". Clicking on "Manage Model"-tab did, however, not show the model-positions plot or Error-distribution. We could save the model to the mount and checked in the keypad that it indeed was loaded. A subsequent test on Saturn and Altair showed that the model was working (pointing error of about 20").

I tried to run the analysis, but could not find the MW4-result file to load it.

Could you shed some light on this, or are these issues already solved in beta-distributions?

thanks in advance,
Nicolàs

**Comment by mworion** [comment]
Nicolas,
could you send me the model file which was generated (should have *.model extension in model folder)?
I try to check.
Michel

**Comment by InFINNity-Deck** [comment]
I will ask the owner, although I fear that none was generated as I could not find it to run it through the analysis.

Nicolàs

**Comment by mworion** [comment]
Hi Nicolas, 
from the log I see that there should be a file existing:

`m-2021-06-27-09-59-20-file`

Please check, if file paths contain white spaces or other "strange" characters as windows sometimes reacts different to MAC or Linux and I do not get these deviation in debugging mode during development.
Michel

**Comment by InFINNity-Deck** [comment]
Hi Michel,

as I feared the model-file was not created. The images-folder does contain the images that were taken by MW4 (it was asked to keep the images), but the model file itself is gone (or was not created?).

Nicolàs

**Comment by InFINNity-Deck** [comment]
Hi Michel,

just now I installed the latest beta version on his laptop, but the cooling button remains unresponsive. When I click the field next to Cooler Temp, I can set the temperature to -20, but it does not accept it. Hitting the Cooler On button does not make it turn blue.

Nicolàs

**Comment by mworion** [comment]
Hi Nicolas,
will have a look this evening. Would you mind to enable trace mode for logging? For issue tracking this helps.
Michel

**Comment by InFINNity-Deck** [comment]
Thanks Michel, next time I will turn on trace mode.

Nicolàs

**Comment by mworion** [comment]
Hi Nicolas,

The coolerOn is fixed in v2.0.0b22. We had some troubles with cameras reporting has cooler, but driver does not support it.
The second I never tested before. As MW4 is a async tool, you could do everything in any order. Starting a second time does not make sense, but leads to a critical situation.
I fixed this (disable start when on pause). This will be in the next beta as well.

In the logs I see still a lot of errors. Therefore a trace mode will be helpful as I currently don't see the segment, which cases the fault.

I recently uploaded this version and it should be easily updatable via internal updater now.

Michel

**Comment by InFINNity-Deck** [comment]
Hi Michel,

thanks for the quick fix! We have the next session planned for early next week, so will let you know the result by then, including a new log-file in trace-mode.

I agree that starting  a second time does not make sense, but we accidentally hit the start-button instead of the pause-button, so it is good that you disabled that now.

Once again many thanks!

Nicolàs

**Comment by InFINNity-Deck** [comment]
Hi Michel,

I am currently assisting my Canadian friend. We just installed 2.0.0b25, but still cannot get the camera to cool. After that tried 2.0.0b22, but that version too did not allow cooling. Could you please check again?

[mw4-2021-07-19.log](https://github.com/mworion/MountWizzard4/files/6838680/mw4-2021-07-19.log)

thanks,
Nicolàs

**Comment by mworion** [comment]
Nicolas,
I think I misinterpreted the ASCOM spec and the defined properties. So HasCooler is a Property to be set in the original ASCOM CCDSimulator, but is not mandatory. Despite this fact CoolerOn is not mandatory nor does it needs to see HasCooler. So now I overwrite theses setting and catch exceptions in case of failing.
v2.0.0b26 should now shut cooler on and off and show the state if the property is implemented in ASCOM driver.
Michel

**Comment by InFINNity-Deck** [comment]
Hi Michel,

Thanks for the quick update!
Indeed, these non-mandatory properties are not the programmer's best friend. We are going to do another run tomorrow, will install the new version first.

Nicolàs

**Comment by InFINNity-Deck** [comment]
Hi Michel,

just tested 2.0.0b26 and it does cool the camera now, we are currently running a 74-point model.
Thanks a bunch again!

with kind regards,
Nicolàs

**Comment by mworion** [comment]
Nicolas,
good to hear. If you don't mind I close the issue. In case of new things, please reopen or open a new one.
Michel
