### ISSUE TITLE
"No QCI Updater available - upload not possible"

### ISSUE THREAD

**Issue by yzhzhang** [mworion/MountWizzard4#197]
Hi,

I re-installed my PC and installed MW4 from scratch, and noticed I cannot update the satellites and/or MPC data. I did just re-install the updater using one of the Firmware updater, but still it looks like MW4 can't operate on it. Is there something I am doing wrong?

Thanks,
Yizhou

![image](https://user-images.githubusercontent.com/79808935/137502983-ebc8d5cc-c5b6-49c6-a037-bc8a63b657f7.png)

**Comment by yzhzhang** [comment]
Hi Michel,

Apologize for the late response. Attached please find the latest log. Its'a bit messy, but you can only look at the last portion starting 10/24/2021. I think debug is on. But story is still pretty short: same issue, and the Updater doesn't got started at all.

Yizhou

[mw4-2021-10-15.log](https://github.com/mworion/MountWizzard4/files/7403886/mw4-2021-10-15.log)

**Comment by mworion** [comment]
Hi Yizhou,
could you tell, which firmware version do you use and what firmwares you already had installed. Please have a look into the 10micron application directory and look, which *.exe files do you find.
Thanks for your help.
Michel

**Comment by yzhzhang** [comment]
Hi Michel,

Sorry for my late response... The setup is in a remote site, and honestly right now I am still be able to use it and manually update the files with the MW4-downloaded data, so I tend to leave it as-is :) I just tried again and same error message... 

The mount is with FW 3.0, and I think I only installed 3.0 firmware installation file if that's what you asking.
"Please feel free to make another install in a new workdir. Please use the actual script from the webpage." Do you mean to download & install MW4 from scratch?

Thanks,
Yizhou

**Comment by mworion** [comment]
No, I have another user, which has from symptom side equal issues, but he is using FW 2.16.x. So his problem might be that MW4 does not focus the right EXE. This is not the point with FW 3.x.
If you are happy, please feel free to use it as it is. If you don't mind, I would make a special build for you with extended logging to improve analyze situation. But this may take some time.
Michel

**Comment by yzhzhang** [comment]
Thanks Michel. Yeah I can give it a try if you have a special version enabling more logging. Thanks!

**Comment by mworion** [comment]
Yizhou,
v2.1.1b1 has an extended logging, please give it a try (hopefully being able to catch the issue) and post the log file.
Issue will not be solved in this release, just for better logging
Michel

**Comment by yzhzhang** [comment]
Hi Michel,

Thanks for the new beta version. Hmmm, this tells something i guess? "Error returned by CreateProcess: (740, 'CreateProcess', 'The requested operation requires elevation.')". How do I change authorization, etc.?

Yizhou
[mw4-2021-11-13.log](https://github.com/mworion/MountWizzard4/files/7532517/mw4-2021-11-13.log)

**Comment by mworion** [comment]
It seem that the 10micron updater could only be used as admin. That's strange. Did you do the install as admin ? If so, please uninstall the updater and reinstall it without admin privileges. Normally you do not need any admin right for using 10micron software or MW4. And it's anyway a security risk in general.
Michel

**Comment by yzhzhang** [comment]
I just un-install and re-installed it. During installatin it didn't pop up to ask for admin rights. 

I don't know if everything installed on C drive requires admin... Is there a way to ask MW4 to direct to other drives? If so I can change the installation to another drive as well.

**Comment by mworion** [comment]
I am not a windows expert, but the install location should not matter. You run the updater with the same account and it does run, correct?

Von meinem iPad gesendet

**Comment by yzhzhang** [comment]
Yeah me neither lol, but I believe it's the same account, as I just run off Windows without changing account and I don't think I have multiple accounts...

BTW, does the keypad arrow (up down left right) not working in 2.1.1b1? It doesn't move my mount, and I went back to 2.0.3 and it does fine..

**Comment by mworion** [comment]
I will build another beta with elevation if that is possible for test
The arrow might be an issue, let’s check.

Von meinem iPad gesendet

**Comment by mworion** [comment]
...I made a service release for it. please upgrade to 2.1.1.

**Comment by yzhzhang** [comment]
Updated to 2.1.1. The keypad works. Thanks!

The updater no. Some errors in the log attached. Thanks!


[mw4-2021-11-13.log](https://github.com/mworion/MountWizzard4/files/7532747/mw4-2021-11-13.log)

**Comment by mworion** [comment]
Hi Yizhou,
finished 2.1.2. Many of the errors (only related to logging) should be gone. No chance to sort the admin topic out from MW4 side (which makes much sense as automation should not be able to increase privileges without user consent !). So from my point you could try to run MW4_Run.bat also as admin (then elevation should not be needed), or we find out, why in your case this request happens (access rights to 10micron app directory,.....)
Michel

**Comment by mworion** [comment]
Hi Yizhou,
please update to 2.1.6 (the latest recent one) and give it another try. I revised a lot of code, hopefully you issue is solved as well.
Michel

**Comment by mworion** [comment]
You should use the 2.1.7b0 version as is still got some improvement in this area.
Michel

**Comment by yzhzhang** [comment]
Hi Michel,

Thank you so much for continuing on this issue!

I updated to 2.1.7b0, but still getting error... Attached please find the log.

It seems downloading the files to the 10micron/updater folder, but can't invoke the updater itself...

Thanks,
Yizhou

[mw4-2021-12-15.log](https://github.com/mworion/MountWizzard4/files/7715552/mw4-2021-12-15.log)

**Comment by mworion** [comment]
Hi Yizhou,
we still have the problem that the updater needs elevation to admin rights. What happens if you start the updater manually? Are you asked for elevation or did you accept this one time for the updater?
Michel

**Comment by yzhzhang** [comment]
> Hi Yizhou, we still have the problem that the updater needs elevation to admin rights. What happens if you start the updater manually? Are you asked for elevation or did you accept this one time for the updater? Michel

Tried to start the updater manually then run this, still same error... Didn't ask for anything, straight same error while the updater was opened already.

It must be on my Windows side as it was working before until I had to re-install the system... But still, mysterious...

Yizhou

**Comment by mworion** [comment]
Yizhou,
what I could offer (as I would like to know what really happens) is to make a teamviewer session. What you could do if you spend some time: Remove the python install (and python launcher) and the updater install from your system, reboot and then reinstall ist from scratch including a new version of MW4 (new install in a different workdir). Please check if the python install and it's options (checkbox add pythonpath) is set like in the documentation.
Another try (bit that's not desired): Run the MW4_Start.bat script as admin and check if it works anyhow. The updater should not be opened before.
Michel

**Comment by yzhzhang** [comment]
> Yizhou, what I could offer (as I would like to know what really happens) is to make a teamviewer session. What you could do if you spend some time: Remove the python install (and python launcher) and the updater install from your system, reboot and then reinstall ist from scratch including a new version of MW4 (new install in a different workdir). Please check if the python install and it's options (checkbox add pythonpath) is set like in the documentation. Another try (bit that's not desired): Run the MW4_Start.bat script as admin and check if it works anyhow. The updater should not be opened before. Michel

Hi Michel,

Thanks a lot for the offer! And thank you VERY much on following up to my issue. As this is at a remote site I tend to keep things as-is... I am a bit hasitate to uninstall if it's working (mostly)... Let me think of it, but perhaps I wish to keep it as-is as of now until my next visit. Hope that makes sense. I am sure it's on my fault as I know it works well before I re-install the system...

Thanks,
Yizhou

**Comment by mworion** [comment]
Yizhou,
No worries, I fully understand this. As I cannot build around admin rights in windows (which is really good as it is part of the security concept of windows), I close the issue for MW4. If you need help, please let me know.
Michel
