### ISSUE TITLE
MW is crashing on start after update to 170

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#69]
Hi Michel,
MW crashes after update to 1.17 after starting immediately. It is not possible to start MW anymore.

Please find the logfile attached. [mw4-2020-10-12.log](https://github.com/mworion/MountWizzard4/files/5366233/mw4-2020-10-12.log)
Thank you!

Cheers
Rüdiger

**Comment by Ruediger3** [comment]
I have just noticed, when I try to start MW again, not even the log file is updated.
The command line window is only flashing and gets closed immediately.

**Comment by mworion** [comment]
Hi Rüdiger,

0.170.1 should solve the issue. Was related to windows automation brought back for windows updater. As 0.170.0 will not start up, please use the batch file for updating.
I revoked 0.170.0.

Michel

**Comment by Ruediger3** [comment]
I have executed "MW4_update.bat" and it downloaded some files, but it is still not starting.

**Comment by Ruediger3** [comment]
Please find attached the output of the loader:
[MW4-Start.txt](https://github.com/mworion/MountWizzard4/files/5366779/MW4-Start.txt)

**Comment by mworion** [comment]
Hi Rüdiger,

The original problem with the update is solved, but your log pointed me to a serious issue the people of the windows automation have right now. So I revoked 0.170.1 as well. If you would like to downgrade, please do so with command window from you work dir:

venv/Scripts/activate
pip install mountwizzard4==0.160.2

I have python 3.8.2 and 3.8.5 in two separate installations running and it seems that from 3.8.2 python they no problem any longer. The python developers themself changed because of the problem (strange to see that), but they have serious troubles to port the solution back to python 3.6 and 3.7 until 3.8.1. So I have to build an exception for that functionality to python 3.8.2 and later.

I got with that change to a new beta. If you just installed python because of MW4 and want to use the features of automation, please deinstall python and take the newest one of 3.8 (which is 3.8.6 right now) and install MW4 in a new folder with the install script. After a first run, you could copy the old work folder content to the new one to keep all your settings and data.

If you have any idea how a user could make the transition better, please let me know.

Michel

**Comment by mworion** [comment]
Uploaded 0.170.2b0, which should run on older python versions without problem (and automation features) and from 3.8.2 ongoing with them...

**Comment by Ruediger3** [comment]
I have just installed python 3.9 and fighting serious issues. The complete enthronement is not working anymore. Python is not anymore working at all. was probably not the best idea :(

**Comment by mworion** [comment]
Add on:
I just read about upgrading python in existing venv's. If that's true, just deinstall old and install new python, change to work dir and enter:

python -m venv --upgrade venv

...but please make a copy of you work dir before. Test this right now, too for making a simpler update

Python 3.9 is not tested from my side!, please stay with 3.8.6

Michel

**Comment by mworion** [comment]
...the new python installer 3.8.6 allows an upgrade (which means no deinstall for older patrons needed...)

**Comment by Ruediger3** [comment]
Your tip came to late. I uninstalled it as recommended. It looks like the installer of MW can not handle 3.9, but only 3.8

**Comment by mworion** [comment]
...and the command above works (at least in 2 of my environments). So the right way might be:
install python 3.8.6 with upgrade feature and run 
python -m venv --upgrade venv
from the work dir upgrades to 3.8.6

Sorry for the late answer.

**Comment by mworion** [comment]
The installer rejects python3.9 as it not tested. The installation therefor is not touched.
Michel

**Comment by Ruediger3** [comment]
ok. Uninstalled 3.9, installed 3.8.6. Ran the venv update. Just installing MW4. It runs, but it is the 1.160.
The update does not work. It only sees a beta.

**Comment by Ruediger3** [comment]
![2020-10-12_21h34_30](https://user-images.githubusercontent.com/65772654/95783732-bbe5d800-0cd2-11eb-884b-cabbd5aef316.png)

How do I get all my profiles, models and all the stuff back?

**Comment by Ruediger3** [comment]
Ok. Got all back. Copied from old folder "model" and "configs".

**Comment by mworion** [comment]
OK, please to an update to 0.170.b1 to make the check final.

**Comment by mworion** [comment]
Seeing it as beta is OK until I know that I don't cause any other problems. Still all my tests went OK (but all had a python >3.8.2 and <3.9)
Michel

**Comment by Ruediger3** [comment]
Ok. I have updated. Seems to work.
I had an entry in the log window with 2b0

![2020-10-12_21h41_16](https://user-images.githubusercontent.com/65772654/95784295-da989e80-0cd3-11eb-8f6e-cb43c222f4e9.png)

**Comment by mworion** [comment]
That's not nice, but without problem.

**Comment by mworion** [comment]
As said: update to 0.170.2b1 should give you the updater automation for comets and earth rotation updates run.

**Comment by Ruediger3** [comment]
Just tested: If the mount is not connected and you cancel 10M tool MW4 fades grey and gets unresponsive until it runs into a time out, which is very long. Maybe a god idea to shorten it.

This update was scary! Time to have beer - cheers to you! Thanks for the support-

**Comment by Ruediger3** [comment]
Tried to open Satellite window and MW froze. Main window is grayed out. No message
![2020-10-12_21h50_01](https://user-images.githubusercontent.com/65772654/95784895-0700ea80-0cd5-11eb-994a-0b510a398036.png)

**Comment by mworion** [comment]
Don't see that, just a message mount not online...

<img width="806" alt="Bildschirmfoto 2020-10-12 um 21 53 35" src="https://user-images.githubusercontent.com/6632980/95785102-6ced7200-0cd5-11eb-863a-96d24a12f957.png">

**Comment by mworion** [comment]
I think I got it. You download the large 150MB Asteroid file (which in some cases take minutes due to speed of their server). If you continue to interact   -> I should remove this big download capability or disable interaction until download is finished (makes not really sense)

**Comment by Ruediger3** [comment]
Maybe a progress indicator would be good?

**Comment by mworion** [comment]
I have to put it in a separat thread and come back when it's finished. It took me now 1:30 min for download and afterwards everything was ok (without interaction in between).
After that evening I have to think about that point.
Thanks for that testing session I really appreciate your involvement!
Michel

**Comment by Ruediger3** [comment]
You are welcome - anytime!!! Definitely!

One suggestions: You call the automation "Minor Planets". This is a bit misleading. Since you do not expect to find the comets there. What about "TLE update"?

**Comment by mworion** [comment]
TLE is the way Satellites are handled. I choose it, because all data is under the label minor planets as all the data comes from the minor planet center and they call their format MPC.
But putting Comets/Asteroids on top might be OK. I'm running out of space in that tab line. I do not want it scrolling.

**Comment by Ruediger3** [comment]
That' s fine! 👍

**Comment by mworion** [comment]
Rüdiger
I added the test in 0.170.3, remove the large file download (it took finally 2 GB of Memory) and added a progress bar and did some naming.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,
just installed an the listed functions work fine. Found another issue, but will create a new issue for that. 
Thanks for the fixes. They look great.

Cheers
Rüdiger

**Comment by Ruediger3** [comment]
Issue solved with 1.170.3
